#My First Workflow

name : workflow1
on: 
   workflow_dispatch:
   push:
env:
   greetings: "Good Morning"
   name: "Mark"
   lastname: "chuah"
jobs:
  build:
    runs-on: ubuntu-latest #ubuntu-20.04 #ubuntu Linux machine provided by GitHub
    environment: dev
    env:
       greetings : "hello"
    steps:
        - name: step1
          run: | 
            echo Application name is ${{ vars.APP_NAME }} and password for the same is $ {{ secrets.SERVER_PASSWORD }}
            echo "$greetings from $name - $name created this ${{ vars.APP_name }} file under repo ${{ GITHUB.REPOSITORY}} and its running on OS ${{RUNNER.OS}}"          
            echo "$ {{ vars.APP_NAME }} is hosted in ${{ vars.PROD_NAME }}"
            sleep 20
          env:
              name: Seong Ping
              greetings: "Hi"
        - name: step2 for testing
          run: |
            cat /etc/os-release
            sleep 10
            hostname
            echo "$greetings from $name"
            touch /tmp/SeongPingfolder1
            
# name is not important in step
        - run: uname -a


  deploy:
    runs-on: ubuntu-latest #ubuntu Linux machine provided by GitHub
    environment: prod
    env:
       lastname : "Chuah"
    steps:
        - name: step1
          run: | 
            echo "$greetings from $name $lastname - $name created this file"
            echo "$ {{ vars.APP_NAME }} is hosted in ${{ vars.SERVER_NAME }}"
            sleep 10
          env:
              name: Seong Ping
        - name: step2 for testing
          run: |
            cat /etc/os-release
            sleep 10
            hostname
            echo "$greetings from $name"
            touch /tmp/SeongPingfolder1

  test:
      runs-on: ubuntu-latest
      environment: test
      env:
        lastname: "Chuah"
      steps: 
        - name: step1
          run: |
            echo "$greetings ! from $name $lastname . $name created this file"
            echo Application name is ${{ vars.APP_NAME }}
            echo " ${{ vars.APP_NAME }} is hosted on ${{ vars.SERVER_NAME }}"
            sleep 5
            
