#My First Workflow

name : workflow1
on: 
   workflow_dispatch:
   push:
jobs:
  job1:
    runs-on: self-hosted #ubuntu-20.04 #ubuntu Linux machine provided by GitHub
    steps:
        - name: step1
          run: | 
            echo "Hello from $name"
            env:
              name: Seong Ping
        - name: step2 for testing
          run: |
            cat /etc/os-release
            hostname
            touch /tmp/SeongPingfolder1
            
# name is not important in step
        - run: uname -a
