#My First Workflow

name : workflow1
on: 
   workflow_dispatch:
   push:
env:
   greetings: "Good Morning"
   name: "Mark"
   lastname: "chuah"
jobs:
  job1:
    runs-on: ubuntu-latest #ubuntu-20.04 #ubuntu Linux machine provided by GitHub
    env:
       greetings : "hello"
    steps:
        - name: step1
          run: | 
            echo "$greetings from $name - $name created this file under repo ${{ GITHUB.REPOSITORY}} and its runningon OS ${{RUNNER.OS}}"          
          env:
              name: Seong Ping
              greetings: "Hi"
        - name: step2 for testing
          run: |
            cat /etc/os-release
            hostname
            echo "$greetings from $name"
            touch /tmp/SeongPingfolder1
            
# name is not important in step
        - run: uname -a


  job2:
    runs-on: ubuntu-latest #ubuntu Linux machine provided by GitHub
    env:
       lastname : "Chuah"
    steps:
        - name: step1
          run: | 
            echo "$greetings from $name $lastname - $name created this file"
          env:
              name: Seong Ping
        - name: step2 for testing
          run: |
            cat /etc/os-release
            hostname
            echo "$greetings from $name"
            touch /tmp/SeongPingfolder1
            
