#My First Workflow

name : workflow1
on: 
   workflow_dispatch:
   push:
jobs:
  job1:
    runs-on: ubuntu-latest #ubuntu Linux machine provided by GitHub
    steps:
        - name: step1
          run: | 
            echo "Hello from Seong Ping"
            sleep 30
        - name: step2 for testing
          run: |
            cat /etc/os-release
            sleep 30
# name is not importenat in step
        - run: uname -a
