#My First Workflow

name : workflow1
on: 
   push
jobs:
  job1:
    runs-on: ubuntu-latest #ubuntu Linux machine provided by GitHub
    steps:
        - name: step1
          run: echo "Hello from Seong Ping"
